spring.datasource.url=jdbc:postgres://ewauvwdrjwhsif:40f10a0f1d03e1f5ce4ba9b604b34b699efc549b6ff9e4f58f5945ed3b944bc5@ec2-52-5-176-53.compute-1.amazonaws.com:5432/d8em178lg67o4t
spring.datasource.username=ewauvwdrjwhsif
spring.datasource.password=40f10a0f1d03e1f5ce4ba9b604b34b699efc549b6ff9e4f58f5945ed3b944bc5
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect